services:
  web:
    build:
      context: ./audiobooks
      dockerfile: Dockerfile.prod
    container_name: django_web
    restart: always
    volumes:
      - /media/pi/ADATA_HM900/media:/app/media
      #- ./audiobooks/media:/app/media
      - ./audiobooks/prodstaticfiles:/app/prodstaticfiles
      - ./audiobooks/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /media/pi/ADATA_HM900/media:/app/media:ro
      #- ./audiobooks/media:/app/media:ro
      - ./audiobooks/prodstaticfiles:/app/prodstaticfiles
    depends_on:
      - web
