# Generated by Django 4.2.16 on 2024-11-11 12:25

from django.db import migrations, models
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_author_image_genre_image_series_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.utils.book_image_upload_path),
        ),
    ]
