# Generated by Django 4.2.16 on 2024-11-11 16:19

from django.db import migrations, models
import django.db.models.deletion
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=store.utils.audio_file_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='store.book')),
            ],
        ),
    ]
