# Generated by Django 4.2.16 on 2025-05-02 14:23

from django.db import migrations, models
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_genre_name_alter_series_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(max_length=400, upload_to=store.utils.audio_file_upload_path),
        ),
    ]
