# Generated by Django 4.2.16 on 2025-11-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_audiofile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'slug']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
